# Generated by Django 6.0 on 2025-12-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlog',
            name='age',
        ),
    ]
